/* Generated by cbindgen — do not edit manually. */

/* Generated with cbindgen:0.29.2 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Span {
  uint32_t start_byte;
  uint32_t end_byte;
  uint8_t r;
  uint8_t g;
  uint8_t b;
  uint8_t a;
  uint8_t font_style;
} Span;

typedef void (*EmitSpanFn)(void *ctx, uint32_t line_index, struct Span span);

void *zintect_create_runtime(void);

void zintect_destroy_runtime(void *handle);

bool zintect_runtime_set_theme(void *handle, const char *theme_json);

void *zintect_create_session(void);

void zintect_destroy_session(void *handle);

bool zintect_session_set_syntax_by_ext(void *session, void *runtime, const char *ext);

bool zintect_session_reset(void *session, void *runtime);

bool zintect_session_highlight_line(void *session,
                                    void *runtime,
                                    const char *line,
                                    uint32_t line_index,
                                    void *ctx,
                                    EmitSpanFn emit);
