/* Generated by cbindgen — do not edit manually. */

/* Generated with cbindgen:0.29.2 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

void *zintect_create_runtime(void);

void zintect_destroy_runtime(void *handle);

void *zintect_create_instance(void);

void zintect_destroy_instance(void *handle);

void zintect_initial_parse(void *runtime,
                           void *instance,
                           const char *buffer,
                           const char *extension);
