/* Generated by cbindgen — do not edit manually. */

/* Generated with cbindgen:0.29.2 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct FffResult {
  /**
   * Whether the operation succeeded.
   */
  bool success;
  /**
   * Opaque pointer payload. May be null.
   */
  void *handle;
} FffResult;

typedef struct FffSpan {
  uint32_t start_byte;
  uint32_t end_byte;
  uint8_t color[4];
  uint8_t font_style;
} FffSpan;

typedef struct FffHighlightResult {
  struct FffSpan *items;
  uint32_t count;
} FffHighlightResult;

void *zintect_create_runtime(void);

void zintect_destroy_runtime(void *handle);

bool zintect_runtime_set_theme(void *handle, const char *theme_json);

void *zintect_create_session(void);

void zintect_destroy_session(void *handle);

bool zintect_session_set_syntax_by_ext(void *session, void *runtime, const char *ext);

bool zintect_session_reset(void *session, void *runtime);

struct FffResult zintect_session_highlight_line(void *session, void *runtime, const char *line);

/**
 * Free a result returned by any `fff_*` function.
 *
 * ## Safety
 * `result_ptr` must be a valid pointer returned by a `fff_*` function.
 */
void fff_free_result(struct FffResult *result_ptr);

/**
 * Free a result returned by any `fff_*` function.
 *
 * ## Safety
 * `result_ptr` must be a valid pointer returned by a `fff_*` function.
 */
void fff_free_highlight_result(struct FffHighlightResult *result_ptr);
